version: '3.7'

volumes:
  meritokrat_db:
    name: meritokrat_db

networks:
  default:
    name: meritokrat
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.1.0/24

  extranet:
    driver: bridge
    external: true
    name: extranet

services:
  web:
    image: nginx:latest
    container_name: meritokrat-web
    environment:
      - NGINX_HOST=meritokrat.org
      - NGINX_PORT=80
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ../meritokrat:/apps/meritokrat
    networks:
      - default
      - extranet
    expose:
      - 80
    links:
      - php56

  php56:
    build:
      context: .
      dockerfile: meritokrat.dockerfile
      args:
        uid: ${UID}
        user: ${USER}
    container_name: meritokrat-php56
    env_file:
      - .env
    volumes:
      - ./etc/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./etc/ssmtp/revaliases:/etc/ssmtp/revaliases
      - ../meritokrat:/apps/meritokrat
    networks:
      - default
    expose:
      - 9000
    links:
      - db
      - memcached
      - redis

  db:
    image: postgres:11.5
    container_name: meritokrat-db
    restart: always
    environment:
      POSTGRES_PASSWORD: '123'
    volumes:
      - meritokrat_db:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.23.1.42
    ports:
      - "15432:5432"

  memcached:
    image: memcached
    container_name: meritokrat-memcached
    restart: always
    networks:
      - default
    expose:
      - 11211

  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    container_name: meritokrat-redis
    restart: always
    networks:
      - default
    expose:
      - 6379
